#include "src/game/envfx_snow.h"

const GeoLayout mario_capless_head_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switch_option_capless_head__no_cap__mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_geo_opt_1_1),
			GEO_BRANCH(1, mario_geo_opt_2_1),
			GEO_BRANCH(1, mario_geo_opt_3_1),
			GEO_BRANCH(1, mario_geo_opt_4_1),
			GEO_BRANCH(1, mario_geo_opt_5_1),
			GEO_BRANCH(1, mario_geo_opt_6_1),
			GEO_BRANCH(1, mario_geo_opt_7_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_switch_option_left_hand_open_left_hand_open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_switch_option_right_hand_open_right_hand_open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_switch_option_right_hand_peace_right_hand_peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_switch_option_right_hand_cap_right_hand_cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_wings_dl_mesh_layer_4_with_layer_4_revert),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_dl_mesh_layer_1_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_dl_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_dl_mesh_layer_1_opt_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_dl_mesh_layer_1_opt_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_dl_mesh_layer_1_opt_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_dl_mesh_layer_1_opt_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_dl_mesh_layer_1_opt_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_4_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_5_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_6_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_7_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_2_opt_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_dl_mesh_layer_1_opt_1_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_2_opt_1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_dl_mesh_layer_1_opt_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_2_opt_1_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_dl_mesh_layer_1_opt_1_opt_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_2_opt_1_opt_4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_dl_mesh_layer_1_opt_1_opt_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_2_opt_1_opt_5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_dl_mesh_layer_1_opt_1_opt_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_2_opt_1_opt_6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_dl_mesh_layer_1_opt_1_opt_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_2_opt_1_opt_7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_dl_mesh_layer_1_opt_1_opt_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_capless_head_armature_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switch_option_capless_head__no_cap__mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_geo_opt_1_1_opt_1),
			GEO_BRANCH(1, mario_geo_opt_2_1_opt_1),
			GEO_BRANCH(1, mario_geo_opt_3_1_opt_1),
			GEO_BRANCH(1, mario_geo_opt_4_1_opt_1),
			GEO_BRANCH(1, mario_geo_opt_5_1_opt_1),
			GEO_BRANCH(1, mario_geo_opt_6_1_opt_1),
			GEO_BRANCH(1, mario_geo_opt_7_1_opt_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_4_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_5_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_6_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_7_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_open_armature_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_switch_option_left_hand_open_left_hand_open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_open_armature_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_switch_option_right_hand_open_right_hand_open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_peace_armature_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_switch_option_right_hand_peace_right_hand_peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_cap_armature_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_switch_option_right_hand_cap_right_hand_cap_mesh_layer_1_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_wing_cap_armature_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_mesh_layer_1_opt_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_wings_dl_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 0, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_pelvis_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_chest_skinned_mesh_layer_1),
					GEO_ASM(0, geo_move_mario_part_from_parent),
					GEO_ASM(0, geo_mario_tilt_torso),
					GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_chest_mesh_layer_1_opt_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_mario_head_rotation),
								GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_dl_mesh_layer_1_opt_1_0),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, mario_geo_opt_1_2_opt_1_opt_1),
												GEO_BRANCH(1, mario_geo_opt_1_2_opt_1_opt_2),
												GEO_BRANCH(1, mario_geo_opt_1_2_opt_1_opt_3),
												GEO_BRANCH(1, mario_geo_opt_1_2_opt_1_opt_4),
												GEO_BRANCH(1, mario_geo_opt_1_2_opt_1_opt_5),
												GEO_BRANCH(1, mario_geo_opt_1_2_opt_1_opt_6),
												GEO_BRANCH(1, mario_geo_opt_1_2_opt_1_opt_7),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, mario_capless_head_armature_opt_1),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 142, -51, 126, -15, 33, -133),
									GEO_OPEN_NODE(),
										GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_wing_dl_L_mesh_layer_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 142, -51, -126, 15, -33, -133),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_wing_dl_R_mesh_layer_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_upper_arm_L_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -10, 79, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_upper_arm_L_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_lower_arm_L_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_lower_arm_L_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(1, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_TRANSPARENT, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_hand_dl_L_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, mario_left_hand_open_armature_opt_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_upper_arm_R_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -10, -79, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_upper_arm_R_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_lower_arm_R_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_lower_arm_R_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_TRANSPARENT, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_hand_dl_R_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, mario_right_hand_open_armature_opt_1),
											GEO_BRANCH(1, mario_right_hand_peace_armature_opt_1),
											GEO_BRANCH(1, mario_right_hand_cap_armature_opt_1),
											GEO_BRANCH(1, mario_right_hand_wing_cap_armature_opt_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_upper_leg_L_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, 42, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_upper_leg_L_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_lower_leg_L_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_lower_leg_L_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_foot_L_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_foot_L_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_upper_leg_R_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, -42, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_upper_leg_R_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_lower_leg_R_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_lower_leg_R_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_foot_dl_R_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_TRANSPARENT, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_foot_dl_R_mesh_layer_1_with_layer_5_revert),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_2_opt_2_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_dl_mesh_layer_1_opt_2_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_2_opt_2_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_dl_mesh_layer_1_opt_2_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_2_opt_2_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_dl_mesh_layer_1_opt_2_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_2_opt_2_opt_4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_dl_mesh_layer_1_opt_2_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_2_opt_2_opt_5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_dl_mesh_layer_1_opt_2_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_2_opt_2_opt_6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_dl_mesh_layer_1_opt_2_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_2_opt_2_opt_7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_dl_mesh_layer_1_opt_2_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_capless_head_armature_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_0),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_geo_opt_1_1_opt_2),
			GEO_BRANCH(1, mario_geo_opt_2_1_opt_2),
			GEO_BRANCH(1, mario_geo_opt_3_1_opt_2),
			GEO_BRANCH(1, mario_geo_opt_4_1_opt_2),
			GEO_BRANCH(1, mario_geo_opt_5_1_opt_2),
			GEO_BRANCH(1, mario_geo_opt_6_1_opt_2),
			GEO_BRANCH(1, mario_geo_opt_7_1_opt_2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_4_1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_5_1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_6_1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_7_1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_open_armature_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_switch_option_left_hand_open_left_hand_open_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_open_armature_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_switch_option_right_hand_open_right_hand_open_mesh_layer_1_opt_2),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_peace_armature_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_switch_option_right_hand_peace_right_hand_peace_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_cap_armature_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_switch_option_right_hand_cap_right_hand_cap_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_wing_cap_armature_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_mesh_layer_1_opt_2),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_wings_dl_mesh_layer_4_with_layer_4_revert),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_pelvis_mesh_layer_1_opt_2),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_chest_skinned_mesh_layer_1_opt_2),
					GEO_ASM(0, geo_move_mario_part_from_parent),
					GEO_ASM(0, geo_mario_tilt_torso),
					GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_chest_mesh_layer_1_opt_2),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_mario_head_rotation),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_dl_mesh_layer_1_opt_2_0),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, mario_geo_opt_2_2_opt_2_opt_1),
												GEO_BRANCH(1, mario_geo_opt_2_2_opt_2_opt_2),
												GEO_BRANCH(1, mario_geo_opt_2_2_opt_2_opt_3),
												GEO_BRANCH(1, mario_geo_opt_2_2_opt_2_opt_4),
												GEO_BRANCH(1, mario_geo_opt_2_2_opt_2_opt_5),
												GEO_BRANCH(1, mario_geo_opt_2_2_opt_2_opt_6),
												GEO_BRANCH(1, mario_geo_opt_2_2_opt_2_opt_7),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, mario_capless_head_armature_opt_2),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
									GEO_OPEN_NODE(),
										GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_ALPHA, mario_wing_dl_L_mesh_layer_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_ALPHA, mario_wing_dl_R_mesh_layer_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_upper_arm_L_skinned_mesh_layer_1_opt_2),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_upper_arm_L_mesh_layer_1_opt_2),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_lower_arm_L_skinned_mesh_layer_1_opt_2),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_lower_arm_L_mesh_layer_1_opt_2),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(1, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_hand_dl_L_mesh_layer_1_opt_2),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, mario_left_hand_open_armature_opt_2),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_upper_arm_R_skinned_mesh_layer_1_opt_2),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, -79, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_upper_arm_R_mesh_layer_1_opt_2),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_lower_arm_R_skinned_mesh_layer_1_opt_2),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_lower_arm_R_mesh_layer_1_opt_2),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_hand_dl_R_mesh_layer_1_opt_2),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, mario_right_hand_open_armature_opt_2),
											GEO_BRANCH(1, mario_right_hand_peace_armature_opt_2),
											GEO_BRANCH(1, mario_right_hand_cap_armature_opt_2),
											GEO_BRANCH(1, mario_right_hand_wing_cap_armature_opt_2),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_upper_leg_L_skinned_mesh_layer_1_opt_2),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_upper_leg_L_mesh_layer_1_opt_2),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_lower_leg_L_skinned_mesh_layer_1_opt_2),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_lower_leg_L_mesh_layer_1_opt_2),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_foot_L_skinned_mesh_layer_1_opt_2),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_foot_L_mesh_layer_1_opt_2),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_upper_leg_R_skinned_mesh_layer_1_opt_2),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_upper_leg_R_mesh_layer_1_opt_2),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_lower_leg_R_skinned_mesh_layer_1_opt_2),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_lower_leg_R_mesh_layer_1_opt_2),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_foot_dl_R_skinned_mesh_layer_1_opt_2),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_foot_dl_R_mesh_layer_1_opt_2_with_layer_1_revert),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_2_opt_3_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_dl_mesh_layer_1_opt_2_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_2_opt_3_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_dl_mesh_layer_1_opt_2_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_2_opt_3_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_dl_mesh_layer_1_opt_2_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_2_opt_3_opt_4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_dl_mesh_layer_1_opt_2_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_2_opt_3_opt_5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_dl_mesh_layer_1_opt_2_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_2_opt_3_opt_6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_dl_mesh_layer_1_opt_2_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_2_opt_3_opt_7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_dl_mesh_layer_1_opt_2_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_capless_head_armature_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_0),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_geo_opt_1_1_opt_3),
			GEO_BRANCH(1, mario_geo_opt_2_1_opt_3),
			GEO_BRANCH(1, mario_geo_opt_3_1_opt_3),
			GEO_BRANCH(1, mario_geo_opt_4_1_opt_3),
			GEO_BRANCH(1, mario_geo_opt_5_1_opt_3),
			GEO_BRANCH(1, mario_geo_opt_6_1_opt_3),
			GEO_BRANCH(1, mario_geo_opt_7_1_opt_3),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_1_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_1_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_1_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_4_1_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_5_1_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_6_1_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_7_1_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_open_armature_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_switch_option_left_hand_open_left_hand_open_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_open_armature_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_switch_option_right_hand_open_right_hand_open_mesh_layer_1_opt_2),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_peace_armature_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_switch_option_right_hand_peace_right_hand_peace_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_cap_armature_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_switch_option_right_hand_cap_right_hand_cap_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_wing_cap_armature_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_mesh_layer_1_opt_2),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_wings_dl_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 0, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_pelvis_mesh_layer_1_opt_2),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_chest_skinned_mesh_layer_1_opt_2),
					GEO_ASM(0, geo_move_mario_part_from_parent),
					GEO_ASM(0, geo_mario_tilt_torso),
					GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_chest_mesh_layer_1_opt_2),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_mario_head_rotation),
								GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_head_dl_mesh_layer_1_opt_2_0),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, mario_geo_opt_3_2_opt_3_opt_1),
												GEO_BRANCH(1, mario_geo_opt_3_2_opt_3_opt_2),
												GEO_BRANCH(1, mario_geo_opt_3_2_opt_3_opt_3),
												GEO_BRANCH(1, mario_geo_opt_3_2_opt_3_opt_4),
												GEO_BRANCH(1, mario_geo_opt_3_2_opt_3_opt_5),
												GEO_BRANCH(1, mario_geo_opt_3_2_opt_3_opt_6),
												GEO_BRANCH(1, mario_geo_opt_3_2_opt_3_opt_7),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, mario_capless_head_armature_opt_3),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 142, -51, 126, -15, 33, -133),
									GEO_OPEN_NODE(),
										GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_wing_dl_L_mesh_layer_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 142, -51, -126, 15, -33, -133),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_wing_dl_R_mesh_layer_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_upper_arm_L_skinned_mesh_layer_1_opt_2),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -10, 79, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_upper_arm_L_mesh_layer_1_opt_2),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_lower_arm_L_skinned_mesh_layer_1_opt_2),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_lower_arm_L_mesh_layer_1_opt_2),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(1, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_TRANSPARENT, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_hand_dl_L_mesh_layer_1_opt_2),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, mario_left_hand_open_armature_opt_3),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_upper_arm_R_skinned_mesh_layer_1_opt_2),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -10, -79, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_upper_arm_R_mesh_layer_1_opt_2),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_lower_arm_R_skinned_mesh_layer_1_opt_2),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_lower_arm_R_mesh_layer_1_opt_2),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_TRANSPARENT, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_hand_dl_R_mesh_layer_1_opt_2),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, mario_right_hand_open_armature_opt_3),
											GEO_BRANCH(1, mario_right_hand_peace_armature_opt_3),
											GEO_BRANCH(1, mario_right_hand_cap_armature_opt_3),
											GEO_BRANCH(1, mario_right_hand_wing_cap_armature_opt_3),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_upper_leg_L_skinned_mesh_layer_1_opt_2),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, 42, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_upper_leg_L_mesh_layer_1_opt_2),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_lower_leg_L_skinned_mesh_layer_1_opt_2),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_lower_leg_L_mesh_layer_1_opt_2),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_foot_L_skinned_mesh_layer_1_opt_2),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_foot_L_mesh_layer_1_opt_2),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_upper_leg_R_skinned_mesh_layer_1_opt_2),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, -42, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_upper_leg_R_mesh_layer_1_opt_2),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_lower_leg_R_skinned_mesh_layer_1_opt_2),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_lower_leg_R_mesh_layer_1_opt_2),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_foot_dl_R_skinned_mesh_layer_1_opt_2),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_TRANSPARENT, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_foot_dl_R_mesh_layer_1_opt_2_with_layer_1_revert),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(99, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_pelvis_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_chest_skinned_mesh_layer_1),
											GEO_ASM(0, geo_move_mario_part_from_parent),
											GEO_ASM(0, geo_mario_tilt_torso),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_chest_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_head_rotation),
														GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																	GEO_OPEN_NODE(),
																		GEO_NODE_START(),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_head_dl_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																		GEO_BRANCH(1, mario_geo_opt_1),
																		GEO_BRANCH(1, mario_geo_opt_2),
																		GEO_BRANCH(1, mario_geo_opt_3),
																		GEO_BRANCH(1, mario_geo_opt_4),
																		GEO_BRANCH(1, mario_geo_opt_5),
																		GEO_BRANCH(1, mario_geo_opt_6),
																		GEO_BRANCH(1, mario_geo_opt_7),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, mario_capless_head_armature),
															GEO_CLOSE_NODE(),
															GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
															GEO_OPEN_NODE(),
																GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
																GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_ALPHA, mario_wing_dl_L_mesh_layer_4),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
															GEO_OPEN_NODE(),
																GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
																GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_ALPHA, mario_wing_dl_R_mesh_layer_4),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_upper_arm_L_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_upper_arm_L_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_lower_arm_L_skinned_mesh_layer_1),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_lower_arm_L_mesh_layer_1),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(1, geo_switch_mario_hand),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
																		GEO_OPEN_NODE(),
																			GEO_ASM(1, geo_mario_hand_foot_scaler),
																			GEO_SCALE(LAYER_FORCE, 65536),
																			GEO_OPEN_NODE(),
																				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_hand_dl_L_mesh_layer_1),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, mario_left_hand_open_armature),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_upper_arm_R_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, -79, NULL),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_upper_arm_R_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_lower_arm_R_skinned_mesh_layer_1),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_lower_arm_R_mesh_layer_1),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_hand),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
																		GEO_OPEN_NODE(),
																			GEO_ASM(0, geo_mario_hand_foot_scaler),
																			GEO_SCALE(LAYER_FORCE, 65536),
																			GEO_OPEN_NODE(),
																				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_hand_dl_R_mesh_layer_1),
																			GEO_CLOSE_NODE(),
																			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, mario_right_hand_open_armature),
																	GEO_BRANCH(1, mario_right_hand_peace_armature),
																	GEO_BRANCH(1, mario_right_hand_cap_armature),
																	GEO_BRANCH(1, mario_right_hand_wing_cap_armature),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_upper_leg_L_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_upper_leg_L_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_lower_leg_L_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_lower_leg_L_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_foot_L_skinned_mesh_layer_1),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_foot_L_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_upper_leg_R_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_upper_leg_R_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_lower_leg_R_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_lower_leg_R_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_foot_dl_R_skinned_mesh_layer_1),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(2, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_foot_dl_R_mesh_layer_1_with_layer_1_revert),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, mario_geo_opt_1_2),
							GEO_BRANCH(1, mario_geo_opt_2_2),
							GEO_BRANCH(1, mario_geo_opt_3_2),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
