extern const GeoLayout mario_capless_head_armature[];
extern const GeoLayout mario_left_hand_open_armature[];
extern const GeoLayout mario_right_hand_open_armature[];
extern const GeoLayout mario_right_hand_peace_armature[];
extern const GeoLayout mario_right_hand_cap_armature[];
extern const GeoLayout mario_right_hand_wing_cap_armature[];
extern const GeoLayout mario_geo_opt_1[];
extern const GeoLayout mario_geo_opt_2[];
extern const GeoLayout mario_geo_opt_3[];
extern const GeoLayout mario_geo_opt_4[];
extern const GeoLayout mario_geo_opt_5[];
extern const GeoLayout mario_geo_opt_6[];
extern const GeoLayout mario_geo_opt_7[];
extern const GeoLayout mario_geo_opt_1_1[];
extern const GeoLayout mario_geo_opt_2_1[];
extern const GeoLayout mario_geo_opt_3_1[];
extern const GeoLayout mario_geo_opt_4_1[];
extern const GeoLayout mario_geo_opt_5_1[];
extern const GeoLayout mario_geo_opt_6_1[];
extern const GeoLayout mario_geo_opt_7_1[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_1[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_2[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_3[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_4[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_5[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_6[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_7[];
extern const GeoLayout mario_capless_head_armature_opt_1[];
extern const GeoLayout mario_geo_opt_1_1_opt_1[];
extern const GeoLayout mario_geo_opt_2_1_opt_1[];
extern const GeoLayout mario_geo_opt_3_1_opt_1[];
extern const GeoLayout mario_geo_opt_4_1_opt_1[];
extern const GeoLayout mario_geo_opt_5_1_opt_1[];
extern const GeoLayout mario_geo_opt_6_1_opt_1[];
extern const GeoLayout mario_geo_opt_7_1_opt_1[];
extern const GeoLayout mario_left_hand_open_armature_opt_1[];
extern const GeoLayout mario_right_hand_open_armature_opt_1[];
extern const GeoLayout mario_right_hand_peace_armature_opt_1[];
extern const GeoLayout mario_right_hand_cap_armature_opt_1[];
extern const GeoLayout mario_right_hand_wing_cap_armature_opt_1[];
extern const GeoLayout mario_geo_opt_1_2[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_1[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_2[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_3[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_4[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_5[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_6[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_7[];
extern const GeoLayout mario_capless_head_armature_opt_2[];
extern const GeoLayout mario_geo_opt_1_1_opt_2[];
extern const GeoLayout mario_geo_opt_2_1_opt_2[];
extern const GeoLayout mario_geo_opt_3_1_opt_2[];
extern const GeoLayout mario_geo_opt_4_1_opt_2[];
extern const GeoLayout mario_geo_opt_5_1_opt_2[];
extern const GeoLayout mario_geo_opt_6_1_opt_2[];
extern const GeoLayout mario_geo_opt_7_1_opt_2[];
extern const GeoLayout mario_left_hand_open_armature_opt_2[];
extern const GeoLayout mario_right_hand_open_armature_opt_2[];
extern const GeoLayout mario_right_hand_peace_armature_opt_2[];
extern const GeoLayout mario_right_hand_cap_armature_opt_2[];
extern const GeoLayout mario_right_hand_wing_cap_armature_opt_2[];
extern const GeoLayout mario_geo_opt_2_2[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_1[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_2[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_3[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_4[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_5[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_6[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_7[];
extern const GeoLayout mario_capless_head_armature_opt_3[];
extern const GeoLayout mario_geo_opt_1_1_opt_3[];
extern const GeoLayout mario_geo_opt_2_1_opt_3[];
extern const GeoLayout mario_geo_opt_3_1_opt_3[];
extern const GeoLayout mario_geo_opt_4_1_opt_3[];
extern const GeoLayout mario_geo_opt_5_1_opt_3[];
extern const GeoLayout mario_geo_opt_6_1_opt_3[];
extern const GeoLayout mario_geo_opt_7_1_opt_3[];
extern const GeoLayout mario_left_hand_open_armature_opt_3[];
extern const GeoLayout mario_right_hand_open_armature_opt_3[];
extern const GeoLayout mario_right_hand_peace_armature_opt_3[];
extern const GeoLayout mario_right_hand_cap_armature_opt_3[];
extern const GeoLayout mario_right_hand_wing_cap_armature_opt_3[];
extern const GeoLayout mario_geo_opt_3_2[];
extern const GeoLayout mario_geo[];
extern u8 mario_fluffa_button_yellow_rgba16[];
extern u8 mario_fluffa_m_logo_ci4[];
extern u8 mario_fluffa_m_logo_pal_ia16[];
extern u8 mario_fluffa_eye_open_ci8[];
extern u8 mario_fluffa_eye_open_pal_rgba16[];
extern u8 mario_wing_i8[];
extern u8 mario_mario_shoe_ci4[];
extern u8 mario_mario_shoe_pal_rgba16[];
extern u8 mario_fluffa_eye_half_closed_ci8[];
extern u8 mario_fluffa_eye_half_closed_pal_rgba16[];
extern u8 mario_fluffa_eye_closed_ci8[];
extern u8 mario_fluffa_eye_closed_pal_rgba16[];
extern u8 mario_fluffa_eye_weak_brow_ci8[];
extern u8 mario_fluffa_eye_weak_brow_pal_rgba16[];
extern u8 mario_fluffa_cyan_eye_pain_alt_ci8[];
extern u8 mario_fluffa_cyan_eye_pain_alt_pal_rgba16[];
extern u8 mario_fluffa_eye_up_alt_ci8[];
extern u8 mario_fluffa_eye_up_alt_pal_rgba16[];
extern u8 mario_fluffa_eye_down_alt_ci8[];
extern u8 mario_fluffa_eye_down_alt_pal_rgba16[];
extern u8 mario_fluffa_eye_x_alt_ci8[];
extern u8 mario_fluffa_eye_x_alt_pal_rgba16[];
extern u8 mario_metal_mario_desat_rgba16[];
extern Vtx mario_pelvis_mesh_layer_1_vtx_0[15];
extern Gfx mario_pelvis_mesh_layer_1_tri_0[];
extern Vtx mario_chest_skinned_mesh_layer_1_vtx_0[8];
extern Gfx mario_chest_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_chest_mesh_layer_1_vtx_0[11];
extern Gfx mario_chest_mesh_layer_1_tri_0[];
extern Vtx mario_chest_mesh_layer_1_vtx_1[31];
extern Gfx mario_chest_mesh_layer_1_tri_1[];
extern Vtx mario_chest_mesh_layer_1_vtx_2[8];
extern Gfx mario_chest_mesh_layer_1_tri_2[];
extern Vtx mario_chest_mesh_layer_1_vtx_3[25];
extern Gfx mario_chest_mesh_layer_1_tri_3[];
extern Vtx mario_head_dl_mesh_layer_1_vtx_0[38];
extern Gfx mario_head_dl_mesh_layer_1_tri_0[];
extern Vtx mario_head_dl_mesh_layer_1_vtx_1[7];
extern Gfx mario_head_dl_mesh_layer_1_tri_1[];
extern Vtx mario_head_dl_mesh_layer_1_vtx_2[81];
extern Gfx mario_head_dl_mesh_layer_1_tri_2[];
extern Vtx mario_head_dl_mesh_layer_1_vtx_3[17];
extern Gfx mario_head_dl_mesh_layer_1_tri_3[];
extern Vtx mario_head_dl_mesh_layer_1_vtx_4[35];
extern Gfx mario_head_dl_mesh_layer_1_tri_4[];
extern Vtx mario_head_dl_mesh_layer_1_vtx_5[49];
extern Gfx mario_head_dl_mesh_layer_1_tri_5[];
extern Vtx mario_switch_option_capless_head__no_cap__mesh_layer_1_vtx_0[102];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1_tri_0[];
extern Vtx mario_switch_option_capless_head__no_cap__mesh_layer_1_vtx_1[17];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1_tri_1[];
extern Vtx mario_switch_option_capless_head__no_cap__mesh_layer_1_vtx_2[96];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1_tri_2[];
extern Vtx mario_switch_option_capless_head__no_cap__mesh_layer_1_vtx_3[49];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1_tri_3[];
extern Vtx mario_wing_dl_L_mesh_layer_4_vtx_0[4];
extern Gfx mario_wing_dl_L_mesh_layer_4_tri_0[];
extern Vtx mario_wing_dl_R_mesh_layer_4_vtx_0[4];
extern Gfx mario_wing_dl_R_mesh_layer_4_tri_0[];
extern Vtx mario_upper_arm_L_skinned_mesh_layer_1_vtx_0[5];
extern Gfx mario_upper_arm_L_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_upper_arm_L_mesh_layer_1_vtx_0[6];
extern Gfx mario_upper_arm_L_mesh_layer_1_tri_0[];
extern Vtx mario_lower_arm_L_skinned_mesh_layer_1_vtx_0[5];
extern Gfx mario_lower_arm_L_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_lower_arm_L_mesh_layer_1_vtx_0[6];
extern Gfx mario_lower_arm_L_mesh_layer_1_tri_0[];
extern Vtx mario_lower_arm_L_mesh_layer_1_vtx_1[5];
extern Gfx mario_lower_arm_L_mesh_layer_1_tri_1[];
extern Vtx mario_lower_arm_L_mesh_layer_1_vtx_2[11];
extern Gfx mario_lower_arm_L_mesh_layer_1_tri_2[];
extern Vtx mario_hand_dl_L_mesh_layer_1_vtx_0[21];
extern Gfx mario_hand_dl_L_mesh_layer_1_tri_0[];
extern Vtx mario_switch_option_left_hand_open_left_hand_open_mesh_layer_1_vtx_0[27];
extern Gfx mario_switch_option_left_hand_open_left_hand_open_mesh_layer_1_tri_0[];
extern Vtx mario_upper_arm_R_skinned_mesh_layer_1_vtx_0[5];
extern Gfx mario_upper_arm_R_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_upper_arm_R_mesh_layer_1_vtx_0[6];
extern Gfx mario_upper_arm_R_mesh_layer_1_tri_0[];
extern Vtx mario_lower_arm_R_skinned_mesh_layer_1_vtx_0[5];
extern Gfx mario_lower_arm_R_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_lower_arm_R_mesh_layer_1_vtx_0[6];
extern Gfx mario_lower_arm_R_mesh_layer_1_tri_0[];
extern Vtx mario_lower_arm_R_mesh_layer_1_vtx_1[5];
extern Gfx mario_lower_arm_R_mesh_layer_1_tri_1[];
extern Vtx mario_lower_arm_R_mesh_layer_1_vtx_2[11];
extern Gfx mario_lower_arm_R_mesh_layer_1_tri_2[];
extern Vtx mario_hand_dl_R_mesh_layer_1_vtx_0[21];
extern Gfx mario_hand_dl_R_mesh_layer_1_tri_0[];
extern Vtx mario_switch_option_right_hand_open_right_hand_open_mesh_layer_1_vtx_0[27];
extern Gfx mario_switch_option_right_hand_open_right_hand_open_mesh_layer_1_tri_0[];
extern Vtx mario_switch_option_right_hand_peace_right_hand_peace_mesh_layer_1_vtx_0[56];
extern Gfx mario_switch_option_right_hand_peace_right_hand_peace_mesh_layer_1_tri_0[];
extern Vtx mario_switch_option_right_hand_cap_right_hand_cap_mesh_layer_1_vtx_0[22];
extern Gfx mario_switch_option_right_hand_cap_right_hand_cap_mesh_layer_1_tri_0[];
extern Vtx mario_switch_option_right_hand_cap_right_hand_cap_mesh_layer_1_vtx_1[7];
extern Gfx mario_switch_option_right_hand_cap_right_hand_cap_mesh_layer_1_tri_1[];
extern Vtx mario_switch_option_right_hand_cap_right_hand_cap_mesh_layer_1_vtx_2[10];
extern Gfx mario_switch_option_right_hand_cap_right_hand_cap_mesh_layer_1_tri_2[];
extern Vtx mario_switch_option_right_hand_cap_right_hand_cap_mesh_layer_1_vtx_3[43];
extern Gfx mario_switch_option_right_hand_cap_right_hand_cap_mesh_layer_1_tri_3[];
extern Vtx mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_mesh_layer_1_vtx_0[20];
extern Gfx mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_mesh_layer_1_tri_0[];
extern Vtx mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_mesh_layer_1_vtx_1[7];
extern Gfx mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_mesh_layer_1_tri_1[];
extern Vtx mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_mesh_layer_1_vtx_2[10];
extern Gfx mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_mesh_layer_1_tri_2[];
extern Vtx mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_mesh_layer_1_vtx_3[43];
extern Gfx mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_mesh_layer_1_tri_3[];
extern Vtx mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_wings_dl_mesh_layer_4_vtx_0[8];
extern Gfx mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_wings_dl_mesh_layer_4_tri_0[];
extern Vtx mario_upper_leg_L_skinned_mesh_layer_1_vtx_0[5];
extern Gfx mario_upper_leg_L_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_upper_leg_L_mesh_layer_1_vtx_0[5];
extern Gfx mario_upper_leg_L_mesh_layer_1_tri_0[];
extern Vtx mario_upper_leg_L_mesh_layer_1_vtx_1[6];
extern Gfx mario_upper_leg_L_mesh_layer_1_tri_1[];
extern Vtx mario_lower_leg_L_skinned_mesh_layer_1_vtx_0[5];
extern Gfx mario_lower_leg_L_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_lower_leg_L_mesh_layer_1_vtx_0[5];
extern Gfx mario_lower_leg_L_mesh_layer_1_tri_0[];
extern Vtx mario_foot_L_skinned_mesh_layer_1_vtx_0[5];
extern Gfx mario_foot_L_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_foot_L_mesh_layer_1_vtx_0[5];
extern Gfx mario_foot_L_mesh_layer_1_tri_0[];
extern Vtx mario_foot_L_mesh_layer_1_vtx_1[26];
extern Gfx mario_foot_L_mesh_layer_1_tri_1[];
extern Vtx mario_upper_leg_R_skinned_mesh_layer_1_vtx_0[5];
extern Gfx mario_upper_leg_R_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_upper_leg_R_mesh_layer_1_vtx_0[5];
extern Gfx mario_upper_leg_R_mesh_layer_1_tri_0[];
extern Vtx mario_upper_leg_R_mesh_layer_1_vtx_1[6];
extern Gfx mario_upper_leg_R_mesh_layer_1_tri_1[];
extern Vtx mario_lower_leg_R_skinned_mesh_layer_1_vtx_0[5];
extern Gfx mario_lower_leg_R_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_lower_leg_R_mesh_layer_1_vtx_0[6];
extern Gfx mario_lower_leg_R_mesh_layer_1_tri_0[];
extern Vtx mario_foot_dl_R_skinned_mesh_layer_1_vtx_0[5];
extern Gfx mario_foot_dl_R_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_foot_dl_R_mesh_layer_1_vtx_0[5];
extern Gfx mario_foot_dl_R_mesh_layer_1_tri_0[];
extern Vtx mario_foot_dl_R_mesh_layer_1_vtx_1[27];
extern Gfx mario_foot_dl_R_mesh_layer_1_tri_1[];
extern Gfx mat_mario_blue[];
extern Gfx mat_revert_mario_blue[];
extern Gfx mat_mario_button_layer1[];
extern Gfx mat_revert_mario_button_layer1[];
extern Gfx mat_mario_red[];
extern Gfx mat_revert_mario_red[];
extern Gfx mat_mario_logo_layer1[];
extern Gfx mat_revert_mario_logo_layer1[];
extern Gfx mat_mario_skin[];
extern Gfx mat_revert_mario_skin[];
extern Gfx mat_mario_eye_open[];
extern Gfx mat_revert_mario_eye_open[];
extern Gfx mat_mario_hair[];
extern Gfx mat_revert_mario_hair[];
extern Gfx mat_mario_mustache[];
extern Gfx mat_revert_mario_mustache[];
extern Gfx mat_mario_wing_combined[];
extern Gfx mat_revert_mario_wing_combined[];
extern Gfx mat_mario_gloves[];
extern Gfx mat_revert_mario_gloves[];
extern Gfx mat_mario_red_dark[];
extern Gfx mat_revert_mario_red_dark[];
extern Gfx mat_mario_shoes[];
extern Gfx mat_revert_mario_shoes[];
extern Gfx mat_mario_eye_half_closed[];
extern Gfx mat_revert_mario_eye_half_closed[];
extern Gfx mat_mario_eye_closed[];
extern Gfx mat_revert_mario_eye_closed[];
extern Gfx mat_mario_eye_weak__look_left_[];
extern Gfx mat_revert_mario_eye_weak__look_left_[];
extern Gfx mat_mario_eye_hurt__look_right_[];
extern Gfx mat_revert_mario_eye_hurt__look_right_[];
extern Gfx mat_mario_eye_up[];
extern Gfx mat_revert_mario_eye_up[];
extern Gfx mat_mario_eye_down[];
extern Gfx mat_revert_mario_eye_down[];
extern Gfx mat_mario_eye_x[];
extern Gfx mat_revert_mario_eye_x[];
extern Gfx mat_revert_mario_button_layer5[];
extern Gfx mat_revert_mario_logo_layer5[];
extern Gfx mat_mario_metal[];
extern Gfx mat_revert_mario_metal[];
extern Gfx mario_pelvis_mesh_layer_1[];
extern Gfx mario_pelvis_mesh_layer_1_opt_2[];
extern Gfx mario_chest_skinned_mesh_layer_1[];
extern Gfx mario_chest_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_chest_mesh_layer_1[];
extern Gfx mario_chest_mesh_layer_1_opt_1[];
extern Gfx mario_chest_mesh_layer_1_opt_2[];
extern Gfx mario_head_dl_mesh_layer_1[];
extern Gfx mario_head_dl_mesh_layer_1_opt_1[];
extern Gfx mario_head_dl_mesh_layer_1_opt_2[];
extern Gfx mario_head_dl_mesh_layer_1_opt_3[];
extern Gfx mario_head_dl_mesh_layer_1_opt_4[];
extern Gfx mario_head_dl_mesh_layer_1_opt_5[];
extern Gfx mario_head_dl_mesh_layer_1_opt_6[];
extern Gfx mario_head_dl_mesh_layer_1_opt_7[];
extern Gfx mario_head_dl_mesh_layer_1_opt_1_0[];
extern Gfx mario_head_dl_mesh_layer_1_opt_1_opt_1[];
extern Gfx mario_head_dl_mesh_layer_1_opt_1_opt_2[];
extern Gfx mario_head_dl_mesh_layer_1_opt_1_opt_3[];
extern Gfx mario_head_dl_mesh_layer_1_opt_1_opt_4[];
extern Gfx mario_head_dl_mesh_layer_1_opt_1_opt_5[];
extern Gfx mario_head_dl_mesh_layer_1_opt_1_opt_6[];
extern Gfx mario_head_dl_mesh_layer_1_opt_1_opt_7[];
extern Gfx mario_head_dl_mesh_layer_1_opt_2_0[];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1[];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_1[];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2[];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_3[];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_4[];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_5[];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_6[];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_7[];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_0[];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_1[];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_2[];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_3[];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_4[];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_5[];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_6[];
extern Gfx mario_switch_option_capless_head__no_cap__mesh_layer_1_opt_2_7[];
extern Gfx mario_wing_dl_L_mesh_layer_4[];
extern Gfx mario_wing_dl_R_mesh_layer_4[];
extern Gfx mario_upper_arm_L_skinned_mesh_layer_1[];
extern Gfx mario_upper_arm_L_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_upper_arm_L_mesh_layer_1[];
extern Gfx mario_upper_arm_L_mesh_layer_1_opt_2[];
extern Gfx mario_lower_arm_L_skinned_mesh_layer_1[];
extern Gfx mario_lower_arm_L_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_lower_arm_L_mesh_layer_1[];
extern Gfx mario_lower_arm_L_mesh_layer_1_opt_2[];
extern Gfx mario_hand_dl_L_mesh_layer_1[];
extern Gfx mario_hand_dl_L_mesh_layer_1_opt_2[];
extern Gfx mario_switch_option_left_hand_open_left_hand_open_mesh_layer_1[];
extern Gfx mario_switch_option_left_hand_open_left_hand_open_mesh_layer_1_opt_2[];
extern Gfx mario_upper_arm_R_skinned_mesh_layer_1[];
extern Gfx mario_upper_arm_R_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_upper_arm_R_mesh_layer_1[];
extern Gfx mario_upper_arm_R_mesh_layer_1_opt_2[];
extern Gfx mario_lower_arm_R_skinned_mesh_layer_1[];
extern Gfx mario_lower_arm_R_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_lower_arm_R_mesh_layer_1[];
extern Gfx mario_lower_arm_R_mesh_layer_1_opt_2[];
extern Gfx mario_hand_dl_R_mesh_layer_1[];
extern Gfx mario_hand_dl_R_mesh_layer_1_opt_2[];
extern Gfx mario_switch_option_right_hand_open_right_hand_open_mesh_layer_1[];
extern Gfx mario_switch_option_right_hand_open_right_hand_open_mesh_layer_1_opt_2[];
extern Gfx mario_switch_option_right_hand_peace_right_hand_peace_mesh_layer_1[];
extern Gfx mario_switch_option_right_hand_peace_right_hand_peace_mesh_layer_1_opt_2[];
extern Gfx mario_switch_option_right_hand_cap_right_hand_cap_mesh_layer_1[];
extern Gfx mario_switch_option_right_hand_cap_right_hand_cap_mesh_layer_1_opt_1[];
extern Gfx mario_switch_option_right_hand_cap_right_hand_cap_mesh_layer_1_opt_2[];
extern Gfx mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_mesh_layer_1[];
extern Gfx mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_mesh_layer_1_opt_1[];
extern Gfx mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_mesh_layer_1_opt_2[];
extern Gfx mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_wings_dl_mesh_layer_4[];
extern Gfx mario_switch_option_right_hand_wing_cap_right_hand_wing_cap_wings_dl_mesh_layer_4_with_layer_4_revert[];
extern Gfx mario_upper_leg_L_skinned_mesh_layer_1[];
extern Gfx mario_upper_leg_L_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_upper_leg_L_mesh_layer_1[];
extern Gfx mario_upper_leg_L_mesh_layer_1_opt_2[];
extern Gfx mario_lower_leg_L_skinned_mesh_layer_1[];
extern Gfx mario_lower_leg_L_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_lower_leg_L_mesh_layer_1[];
extern Gfx mario_lower_leg_L_mesh_layer_1_opt_2[];
extern Gfx mario_foot_L_skinned_mesh_layer_1[];
extern Gfx mario_foot_L_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_foot_L_mesh_layer_1[];
extern Gfx mario_foot_L_mesh_layer_1_opt_2[];
extern Gfx mario_upper_leg_R_skinned_mesh_layer_1[];
extern Gfx mario_upper_leg_R_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_upper_leg_R_mesh_layer_1[];
extern Gfx mario_upper_leg_R_mesh_layer_1_opt_2[];
extern Gfx mario_lower_leg_R_skinned_mesh_layer_1[];
extern Gfx mario_lower_leg_R_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_lower_leg_R_mesh_layer_1[];
extern Gfx mario_lower_leg_R_mesh_layer_1_opt_2[];
extern Gfx mario_foot_dl_R_skinned_mesh_layer_1[];
extern Gfx mario_foot_dl_R_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_foot_dl_R_mesh_layer_1_with_layer_1_revert[];
extern Gfx mario_foot_dl_R_mesh_layer_1_opt_2_with_layer_1_revert[];
extern Gfx mario_foot_dl_R_mesh_layer_1_with_layer_5_revert[];
